#!/usr/bin/env python3
# coding: utf-8

import struct

import click
import requests


entry_struct = struct.Struct("<IHII")  # (account_id, tank_id, battles, wins)


@click.command()
@click.option("--max-id", default=40000000, help="Maximum account ID.", metavar="<id>", show_default=True)
@click.argument("output", metavar="<output>", type=click.File("wb"))
def main(max_id, output):
    "Get account statistics from Wargaming Public API."
    pass


if __name__ == "__main__":
    main()
